### ISSUE TITLE
请问您一个问题，为什么我进游戏后，按鼠标右键，lock_mode 并没有变成True

### ISSUE THREAD

**Issue by Univercp** [brillian32/APEX_yolov5_assist#12]
尊敬的作者：
        您好，我在游戏中鼠标或者键盘输入（操作），程序并没有因为我在这样，程序lock_mode 并没有改变值，然后就锁不了人物。
  接着，我直接设定lock_mode=True ，但在游戏里会一直锁着人，影响游戏体验。请问这个问题怎么解决，是鼠标驱动版本的问题么？

**Comment by brillian32** [comment]
ghub驱动问题，可以不是ghub驱动，用其他api也行

**Comment by brillian32** [comment]
ghub需要用老版本
