### ISSUE TITLE
有识别框但是鼠标不移动，疑似是Ghub问题？

### ISSUE THREAD

**Issue by lhawx0** [brillian32/APEX_yolov5_assist#7]
我以前自己弄的时候用过其他的libraries来移动鼠标，没找到Ghub驱动的用法
怎样调试Ghub驱动？能否指路一下？

**Comment by azubu23202869** [comment]
本身使用也是不會移動

**Comment by lhawx0** [comment]
> 

我之前试用的时候LG Ghub是2022的版本，直接把ghub的驱动移动鼠标注释掉了
暂时用的SendInput

把Ghub换回2021.11版之后gmok就变false了

**Comment by lhawx0** [comment]
GHUB 2020.8 和 2021.4  版本可以移动鼠标

**Comment by azubu23202869** [comment]
有舊版的下載位置?

**Comment by azubu23202869** [comment]
2021.11可以

**Comment by brillian32** [comment]
评论正解
